//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTranslateExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTranslateExtension.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bing.
        /// </summary>
        internal static string BingTranslate {
            get {
                return ResourceManager.GetString("BingTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines whether google translate is enabled.
        /// </summary>
        internal static string BingTranslateDescription {
            get {
                return ResourceManager.GetString("BingTranslateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API Key
        ///Please enter the key in format
        ///DeepL-Auth-Key {API KEY}.
        /// </summary>
        internal static string DeeplApiKey {
            get {
                return ResourceManager.GetString("DeeplApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeepL Translate (use only when the API key is set).
        /// </summary>
        internal static string DeepLTranslate {
            get {
                return ResourceManager.GetString("DeepLTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines whether DeepL translate is enabled.
        /// </summary>
        internal static string DeepLTranslateDescription {
            get {
                return ResourceManager.GetString("DeepLTranslateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default target language code.
        /// </summary>
        internal static string DefaultTargetLanguageCode {
            get {
                return ResourceManager.GetString("DefaultTargetLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The target language to use by default.
        /// </summary>
        internal static string DefaultTargetLanguageCodeDescription {
            get {
                return ResourceManager.GetString("DefaultTargetLanguageCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled providers.
        /// </summary>
        internal static string EnabledProviders {
            get {
                return ResourceManager.GetString("EnabledProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Translate.
        /// </summary>
        internal static string GoogleTranslate {
            get {
                return ResourceManager.GetString("GoogleTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines whether google translate is enabled.
        /// </summary>
        internal static string GoogleTranslateDescription {
            get {
                return ResourceManager.GetString("GoogleTranslateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines the number of history items to show from previous translations.
        /// </summary>
        internal static string HistoryDescriptionMessage {
            get {
                return ResourceManager.GetString("HistoryDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation history.
        /// </summary>
        internal static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid API key.
        /// </summary>
        internal static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsoft Azure.
        /// </summary>
        internal static string MicrosoftAzureTranslate {
            get {
                return ResourceManager.GetString("MicrosoftAzureTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines whether Azure translate is enabled.
        /// </summary>
        internal static string MicrosoftAzureTranslateDescription {
            get {
                return ResourceManager.GetString("MicrosoftAzureTranslateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Too many requests, please try again later.
        /// </summary>
        internal static string TooManyRequestsMessage {
            get {
                return ResourceManager.GetString("TooManyRequestsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred during translation.
        /// </summary>
        internal static string TranslationErrorMessage {
            get {
                return ResourceManager.GetString("TranslationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout in milliseconds for each translation service. -1 stands for infinite timeout..
        /// </summary>
        internal static string TranslationTimeoutDescription {
            get {
                return ResourceManager.GetString("TranslationTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation timeout.
        /// </summary>
        internal static string TranslationTimeoutTitle {
            get {
                return ResourceManager.GetString("TranslationTimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandex Translate.
        /// </summary>
        internal static string YandexTranslate {
            get {
                return ResourceManager.GetString("YandexTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determines whether yandex translate is enabled.
        /// </summary>
        internal static string YandexTranslateDescription {
            get {
                return ResourceManager.GetString("YandexTranslateDescription", resourceCulture);
            }
        }
    }
}
